---
 - hosts: all
   remote_user: root
   become: yes
   become_user: root
        
   tasks:
    - name: install the latest version of Apache
      yum:
       name: httpd
       state: latest
       
    - name: replace
      lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: 'Listen 80'
       line: 'Listen 81'
       
    - name: start the httpd service
      service: name=httpd state=started
      
    - name: Open port 81
      firewalld: 
       port: 81/tcp
       permanent: true 
       state: enabled
    
    - name: start the firewalld service
      service: name=firewalld state=restarted
