---
 - hosts: localhost
   remote_user: root
   become: yes
   become_user: root
   
   vars:
     ansible_become_pass: "kovair@123"
     ansible_connection: "ssh"
     ansible_ssh_user: "root"
     ansible_ssh_pass: "kov$2010$air"
 
   tasks:
    - name: Install specific version of git
      yum:  
        name: git-1.8.3.1-6.el7
        state: present
